### PR TITLE
Added main menu binding option

### PR DESCRIPTION
**Pull request by madmodder123**
If your controllers start/select button is not detected as "pad_back" you won't be able to open the pause menu while in-game, by adding the option to bind it it allows users to use controller-only setups (such as RetroPie)

See https://github.com/RetroPie/RetroPie-Setup/pull/3203

I will also create a pull request upstream as the files have changed.

### CODE REVIEW

**Comment by drfrag666** [comment]
Seems you've made the PR from the wrong branch, the revert changes commit does nothing here.
But what is this for? In that case you won't be able to open the menu anyway.

**Comment by madmodder123** [comment]
> 
> 
> Seems you've made the PR from the wrong branch, the revert changes commit does nothing here.
> But what is this for? In that case you won't be able to open the menu anyway.

I had initially used a different version of menudef.txt so I had to make a separate commit so the PR wouldn't try to revert any updates this branch already had.

So when playing on Raspberry Pi 4 4GB (RetroPie) the controller doesn't always enumerate the select/start buttons as "pad_back"/"pad_start" (Mine enumerate as "JOY9" & "JOY10") so you can get into the game but can't quit or open the menu unless you grab a keyboard.

defbinds.txt uses these:
pad_start pause
pad_back menu_main

So I just made this commit so it adds a binding for the menu button in the control configuration so you can have a controller only setup. (There is already a binding for the pause command so that was untouched).

I just added these lines to these files.

language.enu
CNTRLMNU_OPEN_MAIN = "Open Main Menu";

menudef.txt
Control "$CNTRLMNU_OPEN_MAIN" , "menu_main"

**Comment by drfrag666** [comment]
You mean that branch not this one, those changes you mention are not here.
But my point still stands, you add the binding to the menu but unless i'm missing something you cannot open the menu to change it anyway.

**Comment by madmodder123** [comment]
> 
> 
> You mean that branch not this one, those changes you mention are not here.
> But my point still stands, you add the binding to the menu but unless i'm missing something you cannot open the menu to change it anyway.

You can set up the binding in the config on the main menu upon first launch before you load into a level

**Comment by drfrag666** [comment]
But i guess that's on the RetroPie version of LZDoom not here, the main menu is not opened automatically.

**Comment by drfrag666** [comment]
Merged manually here: https://github.com/drfrag666/gzdoom/commit/d9e32612cf9d85f11c3e71344f31f49b09a04d71

**Pull request closed without merging**
