### PR TITLE
Fixed issue with UniqueList and portals creation

### PR DESCRIPTION
**Pull request by emawind84**
- fixed issue with UniqueList
Added memset after creation of new pointer. This was causing massive drop of framerate on Oculus Quest (Android) when looking outside, with multiple GLSkyInfo object created, memcmp always failed with return -1 when dealing with GLSkyInfo
- added option to switch on/off the skydome in display options
- when the skydome is disabled the background color will match the color of the texture of the skydome to keep some immersion during gameplay

### CODE REVIEW

**Comment by emawind84** [comment]
Currently the skydome on/off option works only when using opengl rendering

**Comment by drfrag666** [comment]
Yes, it should be under OpenGL options. Have you used UTF-8 without BOM? Could you combine both commits into one?

**Comment by emawind84** [comment]
> Yes, it should be under OpenGL options. Have you used UTF-8 without BOM? Could you combine both commits into one?

I will check the encoding and do the pull request again

**Comment by drfrag666** [comment]
You can force push to the same branch. For me performance with skyboxes is fine on windows, are you sure this is not an android specific issue?

**Comment by emawind84** [comment]
> You can force push to the same branch. For me performance with skyboxes is fine on windows, are you sure this is not an android specific issue?

The toggle for the skydome helps a lot on android, regarding the uniquelist, the issue is present on android, from my test, but not on pc, the implementation seems not correct nevertheless.

**Comment by alexey-lysiuk** [comment]
>  Pull request for one line of code is pointless.

You are wrong. Number of changed lines has nothing to do with PR's usefulness.
It's a bad idea to modify unrelated code in one PR. When all changes serve one purpose, and do it right, number of lines is a pointless metric.

**Comment by emawind84** [comment]
> >  Pull request for one line of code is pointless.
> 
> You are wrong. Number of changed lines has nothing to do with PR's usefulness.
> It's a bad idea to modify unrelated code in one PR. When all changes serve one purpose, and do it right, number of lines is a pointless metric.

You are right, just bad use of words on my part, just let me know if I should make a pr for the changes regarding the UniqueList class.

**Pull request closed without merging**
